# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
#    subtype: core                 # plugin subtype (if applicable)
    description:                  # Alternative: description in multiple languages
        de: 'Blockly - graphischer Editor für Logiken - Noch in der Entwicklung, nicht für die Nutzung gedacht'
        en: 'Blockly - graphical editor for logics - Still in development, not for use'
    maintainer: msinn, psilo909
#    tester: '?'
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/959964-support-thread-für-das-backend-plugin

    version: 1.3a.0                # Plugin version
    sh_minversion: 1.3a            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Blockly             # class containing the plugin
    
parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
#    updates_allowed:
#        type: bool
#        default: True
#        description:
#            de: 'Update von Werten durch das Backend Plugin ist erlaubt'
#            en: 'Update of values through the backend plugin is allowed'


item_attributes:
    # Definition of item attributes defined by this plugin
    
